name: document_protos

on:
  pull_request:
    branches: [master]
    paths:
      - "**.proto"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check pwd
        run: echo $(pwd)

      - name: build_html
        run: docker run --rm --platform linux/amd64  -v $(pwd)/docs:/out -v $(pwd)/src/proto:/protos pseudomuto/protoc-gen-doc --doc_opt=html,protos.html

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: bayesmix-devs
          message: "auto update of docs/protos.html"
          add: "docs/protos.html"
