name: Publish Docker image

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.MARIO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.MARIO_DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata for bayesmix_base repo
        id: metadata_base
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mberaha/bayesmix_base
      
      - name: Build and push bayesmix_base
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: docker/base/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: mberaha/bayesmix_base:latest
          
      - name: Extract metadata bayesmix_test repo
        id: metadata_test
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mberaha/bayesmix_test
      
      - name: Build and push bayesmix_test
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: docker/test/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: mberaha/bayesmix_test:latest   
